<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Gerar Certificado PDF em PHP - Enviando por e-mail</title>
    <link rel="stylesheet" href="/libs/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/libs/bootstrap/css/bootstrap-theme.min.css" />
</head>
<body>
    <div class="container">
        <form class="form-horizontal" action="/generate" method="post"  id="contact_form">
            <fieldset>
                <h1 class="text-center">Gere AGORA seu Certificado Online</h1>
                <hr />
                <div class="form-group">
                    <label class="col-md-4 control-label">Nome</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input  name="nome" placeholder="Nome completo" class="form-control"  type="text">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">E-Mail</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                            <input name="email" placeholder="E-Mail" class="form-control"  type="text">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" >CPF</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-barcode"></i></span>
                            <input name="cpf" placeholder="CPF" class="form-control"  type="text" maxlength="14" onkeypress="formatar('###.###.###-##', this);">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label"></label>
                    <div class="col-md-4">
                        <button type="submit" class="btn btn-primary btn-lg col-md-12" >
                            Gerar Certificado
                            <span class="glyphicon glyphicon-download-alt"></span>
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

    <script src='/libs/jquery/jquery.min.js'></script>
    <script src='/libs/bootstrap/js/bootstrap.min.js'></script>

    <script>
        function formatar(mascara, documento){
            var i = documento.value.length;
            var saida = mascara.substring(0,1);
            var texto = mascara.substring(i);
            if (texto.substring(0,1) != saida){documento.value += texto.substring(0,1);}
        }
    </script>
</body>
</html>